#Server Port
server:
  port: 8989

# Bean Override
---
spring:
  main:
    allow-bean-definition-overriding: true

#Cassandra DB
---
spring:
  data:
    cassandra:
      cluster-name: My Cluster
      contact-points: 35.223.150.209,35.224.1.160,35.193.55.3
      keyspace-name: vault
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      consistency-level: ONE
      connect-timeout: 10000ms
      read-timeout: 10000ms
      pool:
        pool-timeout: 10000ms

# Application Business Properties
records:
  max-limit: 100
  initial-count: 20
  page-no: 0

# Logging
logging:
  level:
    com:
      showtime:
        authserver: DEBUG
    # org.springframework: debug
    # org.springframework.security: error


# Feign Client
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

#Cloud Config Server 
---
spring:
  cloud:
    config:
      uri: http://localhost:8888

# Kafka Config
kafka:
  bootstrap-servers: 35.193.55.3:9092
  topic-name: register_new_user