#Server Port
server:
  port: 8100


#Cassandra DB
---
spring:
  data:
    cassandra:
      cluster-name: My Cluster
      contact-points: 35.223.150.209
      keyspace-name: show_time
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      consistency-level: ONE
      connect-timeout: 10000ms
      read-timeout: 10000ms
      pool:
        pool-timeout: 10000ms

# Logging
logging:
  level:
    com:
      showtime:
        userservice: DEBUG


#Cloud Config Server 
--- 
spring:   
   cloud:
    config: 
      uri: http://localhost:8888   

